development:
  adapter: mysql
  database: spielvolk
  pool: 5
  timeout: 5000
  host: localhost
  user: root
  password: railsrails

test:
  adapter: mysql
  database: spielvolk
  pool: 5
  timeout: 5000
  host: localhost
  user: root
  password: railsrails

production:
  adapter: mysql
  encoding: utf8
  database: spielvolk_ch_prod
  username: user60
  password: "nu1vsctm"
  host: 77.95.121.153
